import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SurveyProvider } from "../context/SurveyContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ESAWAS DMA Org-level Tool",
  description: "Generated by ali-tech-solns",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SurveyProvider>{children}</SurveyProvider>
      </body>
    </html>
  );
}
